### ISSUE TITLE
Displaying collections with unindexed fields

### ISSUE THREAD

**Issue by echo-slam-jam** [bfritscher/typesense-dashboard#1]
Hi, I'm using your dashboard for monitoring my typesense collection and it is really helpful!

However, I can't view my collection's documents when there is an unindexed field.

Is this intentional and can this be fixed?
In this example collection, I have two fields, "title" and "unindexed"

unindexed is only checked as optional

![image](https://user-images.githubusercontent.com/53904943/129327277-7ba23dbf-34c0-42f3-a4ea-255f6d2625a6.png)

**Comment by bfritscher** [comment]
Thanks for your report, In my test I did not explicitly declare unindex fields as you can provide additional data and it is saved without declaring it. The search view displays this data below even if not in the schema. But I managed to fix the filter to make the instantsearch component initialise properly.

**Comment by echo-slam-jam** [comment]
thanks :)
