### ISSUE TITLE
Docker image building

### ISSUE THREAD

**Issue by pbek** [bfritscher/typesense-dashboard#12]
Thank you for this awesome tool!
It would be great if a docker image would be built on github directly.
I did that now on https://github.com/digital-blueprint/typesense-dashboard/pkgs/container/typesense-dashboard.

**Comment by pbek** [comment]
I made a PR on #13.

**Comment by bfritscher** [comment]
Thanks for your contribution!

**Comment by pbek** [comment]
Awesome, I'll be using https://github.com/bfritscher/typesense-dashboard/pkgs/container/typesense-dashboard from now on. 😁
