### ISSUE TITLE
Feature request - path field

### ISSUE THREAD

**Issue by minhazma** [bfritscher/typesense-dashboard#15]
Could you add a path field to so that typesense can be run on a non-root location.

var typesense = new Typesense.Client({
    'masterNode': {
      'host': 'example.com',
      'port': '80',
      'path': '/typesense', ---------> THIS
      'protocol': 'http',
      'apiKey': 'abcd'
    }
    'timeoutSeconds': 10
  })

**Comment by bfritscher** [comment]
Ok added in latest version 1.2.2
