### ISSUE TITLE
Displaying collection with wildcard (*) in field name

### ISSUE THREAD

**Issue by Pochwar** [bfritscher/typesense-dashboard#22]
Hi, I'm using Typesense Dashboard to display my collections, and it's a great tool!
But it seems that I can't view my collections when I have a field with a wildcard in the name.

For example : `{ name: 'category.*', type: 'string[]', facet: 'true' }`

I got the following error : "Error: 404 - Could not find a field named `category.*` in the schema."

However, everything works well in my application, so I think it might be a bug in Typesense Dashboard?

**Comment by bfritscher** [comment]
Hi, can you provide some more details?  Do you mean on the "Search" page?
Search page uses the instantsearch adapter and must define the existing fields for filters and faceting 
You define a regex field therefore any fieldname starting with category is possible to exist. Any idea how this should be handled? Have you some examples of your end fieldnames? category_x, category_y. Or do you use  ".*" as litteral?
It may be possible to show the collection content, by not using the field in any of the filters, I will look into this.

**Comment by Pochwar** [comment]
Hi, thank you for correcting this quickly!

**> Hi, can you provide some more details? Do you mean on the "Search" page?**
yes the issue occured on the search page

**> Any idea how this should be handled?** 
It should be just ignored I suppose

**> Have you some examples of your end fieldnames? category_x, category_y. Or do you use ".*" as litteral?**
No, I do not use ".*" as litteral, it's a wildcard as defined in the [documentation](https://typesense.org/docs/0.23.1/api/collections.html#with-auto-schema-detection). So concretely my fields are "category.lvl0", "category.lvl1", "category.lvl2" and so on.

I use your dashboard with docker compose, but it seems that there is no update for the image in the docker hub.
Are you planning to update soon?

**Comment by Pochwar** [comment]
Hum, I don't know, I just run this command : `docker pull funxtionatics/typesense-dashboard:latest` in my terminal and the output is :
```
latest: Pulling from funxtionatics/typesense-dashboard
Digest: sha256:3a6d77812247ef30ff9733a9ed88c21cfab7fd780b208eba73de052633ad6b2d
Status: Image is up to date for funxtionatics/typesense-dashboard:latest
docker.io/funxtionatics/typesense-dashboard:latest
```
I think it comes from Docker Hub where I can see that the "latest" tag's last push is 10 months old: https://hub.docker.com/r/funxtionatics/typesense-dashboard/tags

How can I tell docker to fetch from ghcr.io/bfritscher/typesense-dashboard:latest instead ?

**Comment by Pochwar** [comment]
Ok, I just change 
```
    typesense-dashboard:
        image: funxtionatics/typesense-dashboard:latest
        restart: always
        ports:
            - 9999:80
  ```
to 
```
    typesense-dashboard:
        image: ghcr.io/bfritscher/typesense-dashboard:latest
        restart: always
        ports:
            - 9999:80
```
in my docker-compose.yml file and it's ok :)

Maybe you could update image in Docker Hub for those who, like me, will retrieve the image here

**Comment by bfritscher** [comment]
This is not my own docker hub location, so I have no control over it. 
Since all the restrictions docker imposed on the free account. I strongly prefer using github as image repository.
However, I setup the script to also push the image to my own docker hub account https://hub.docker.com/r/bfritscher/typesense-dashboard

I recommend sticking with: ghcr.io/bfritscher/typesense-dashboard:latest

Regards,
