### ISSUE TITLE
Versioned docker images?

### ISSUE THREAD

**Issue by JaneJeon** [bfritscher/typesense-dashboard#26]
Hello, I'm someone who's interested in self hosting this on my docker setup; however, it would be really nice to have the docker image be versioned so that i _know_ which one works for me and which one doesn't, and I can easily roll back/change versions.

Thank you.

**Comment by JaneJeon** [comment]
(at the moment the only option is to use `:latest`, which obviously isn't too sustainable to have in a hosting setup over long periods of time)

**Comment by bfritscher** [comment]
based on the doc of the action in am using https://github.com/macbre/push-to-ghcr it should be adding the tags, but somehow it does not :-(

**Comment by JaneJeon** [comment]
Something I do is that I tag all of my images, individually, in the CI: https://github.com/JaneJeon/blink/blob/master/.circleci/config.yml#L67-L76 (this is CircleCI, but the same steps could be used to build & publish said tags to GHCR in one CI step)

**Comment by bfritscher** [comment]
fixed my workflow, tag and assets building now works on new release published event
