### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by arpanbag001** [bfritscher/typesense-dashboard#27]
I am unable to connect to my server running on AWS EC2.

I have updated SG to allow all incoming traffic to the port. Have `--enable-cors`
If I send GET request to the server's IP: `/health` , I get `ok:true` , via Postman or any browser.
Yet, when I'm trying to access it through typesense dashboard, I'm getting Network Error

**Comment by bfritscher** [comment]
This sounds like a cors issue are you sure that it is enabled? Does the network error mention cors?

**Comment by arpanbag001** [comment]
The issue was because of "MixedContent", i.e. loading http content (connecting to server) from https site ( https://bfritscher.github.io/typesense-dashboard )

Fixed by:

`Allow Mixed Content in Your Browser: This is not recommended for production environments, but if you're just testing something locally, you can configure your browser to allow mixed content. In Google Chrome, you can click on the padlock icon in the address bar, then site settings, then change the Insecure content setting to "Allow". Remember to change it back when you're done.`

Suggesting library author to update the Readme and highlight this info, so that new users can take actions
