### ISSUE TITLE
[FEAT] Improve discoverability of collection actions DELETE, import, export

### ISSUE THREAD

**Issue by jeanmatthieud** [bfritscher/typesense-dashboard#28]
It's not possible to delete a collection.

I believe that is was possible in a previous release

**Comment by jeanmatthieud** [comment]
Sorry I didn't found the menu

**Comment by fharper** [comment]
It took me a while to find how to do this also, so for those looking how to do this.
- Select the collection you want to delete.
- On the left menu, click on `Schema`.
- There is a red button named `DROP COLLECTION` at the top right corner to delete the collection.

**Comment by bfritscher** [comment]
There is a menu with three dots, but interface may need improvement to make mit more discoverable

<img width="528" alt="image" src="https://github.com/bfritscher/typesense-dashboard/assets/338973/67439a0a-91df-40b1-a94a-686bd22177fe">

Suggestions welcome

**Comment by fharper** [comment]
Oh, the dots are clear in light mode, but the contrast isn't good enough for me in dark mode, so I suggest maybe making them white in that case.
