### ISSUE TITLE
Not able to use self signed  certificates (https)

### ISSUE THREAD

**Issue by option-greek** [bfritscher/typesense-dashboard#3]
Hello,
Is it possible to allow use of self signed certificates. Currently we use https but with self signed cert. If there is a checkbox to enable it some where during login it will be great!

**Comment by bfritscher** [comment]
Hi do you have an error? In desktop/electron or web version?

**Comment by option-greek** [comment]
Attaching the screenshot. This is in desktop (windows 10 64bit
<img width="909" alt="error_typesense_dashboard" src="https://user-images.githubusercontent.com/1430307/144558664-f3b02121-6101-4392-a516-808d3e20b0ca.png">
).

**Comment by bfritscher** [comment]
@option-greek  can you check if this new version works? There is a TLS check toggle at login https://github.com/bfritscher/typesense-dashboard/releases/tag/v1.0.1

**Comment by option-greek** [comment]
Thank you @bfritscher. It works great!
