### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by isAlmogK** [bfritscher/typesense-dashboard#30]
Is this project still alive and being matained?

**Comment by bfritscher** [comment]
Based on the fact that issues are regulary opened and closed I would say yes? What makes you think otherwise? What feature are you missing?

**Comment by isAlmogK** [comment]
Thanks, wanted to make sure right now less about the features but running into a couple bugs, I'm getting a blank page after the fist login when I come back to dashboard for example

**Comment by bfritscher** [comment]
I added issues templates, feel free to open a new issue with detailled descriptions of the bug and steps to reproduce them if possible.
