### ISSUE TITLE
Hide vector values in typesense dashboard

### ISSUE THREAD

**Issue by jsalts** [bfritscher/typesense-dashboard#32]
Typesense is increasingly becoming a tool for vector search. Typesense dashboard should hide these values as they aren't particularly useful for humans to read. 

**Is your feature request related to a problem? Please describe.**

Documents are too difficult to browse when vectors are fully displayed.
![image](https://github.com/bfritscher/typesense-dashboard/assets/5424155/6d6034f4-bbda-40d2-a19d-dc035b0dadc3)

**Describe the solution you'd like**
Hide vector values with option to expand.

**Comment by bfritscher** [comment]
Hi,
Thanks for the suggestion. As there is no way to detect if a field contains
vectors we need either naming convention or a custom setting for each
collection. Currently all settings data is only client side or via a fixed
config file for connections. A global regex setting to filter fields for
each connection could also be an option.

**Comment by jsalts** [comment]
I'd suggest having an expand/contract menu if a field is longer than X characters (defaulted to contracted) unless the length of all fields is below Y characters.
