### ISSUE TITLE
Sort feature

### ISSUE THREAD

**Issue by shidcordero** [bfritscher/typesense-dashboard#4]
Will there be a sort feature for this?

**Comment by bfritscher** [comment]
Hi, the dashboard is mainly an ui for admin part. Browsing is done via the typesense-instantsearch-adapter if it is compatible with sorting feature of instantsearch.js.
Sorting is mostly done in the frontend client you will program to connect to typesense and not necessarly in the admin tool. 
What might be in the futur is a custom query interface.

What is your use case for needing sorting in the admin dashboard UI?

**Comment by JZubero** [comment]
@bfritscher Since sorting by string fields landed in the latest version of typesense (0.23.1) this could be worth a review? In the schema overview, the new sort flag (on per-field basis) is not getting displayed and it's also not available as sort option.

**Comment by bfritscher** [comment]
@JZubero Thanks for the suggestion I added the missing option.

**Comment by JZubero** [comment]
@bfritscher Wow, that was fast. Appreciated :+1: Confirming that it's working well in v1.2.1.
