### ISSUE TITLE
How to run the electron app in linux ?

### ISSUE THREAD

**Issue by option-greek** [bfritscher/typesense-dashboard#5]
Hi @bfritscher ,
     I downloaded the Linux zip but I don't know what to do with it. Usually there will be some .sh or some file to run. But in this package there are only .bin files. I'm trying to run this in Fedora 35. Any idea how to launch it.

**Comment by bfritscher** [comment]
Hi, I packaged it on windows :-(, but I juste tested it in a VM on Ubuntu.
It does not work directly in Nautilus (see https://stackoverflow.com/questions/55060402/electron-executable-not-recognized-by-nautilus)
In a terminal: I had to `chmod +x the 'Typesense Dashboard'`, then I can run it with `./'Typesense Dashboard'`

**Comment by option-greek** [comment]
Thanks @bfritscher . That worked. May be this can be part of the readme now :). 

Also, the other fix you made to make self signed certs work doesn't seem to be in the linux builds. If you don't mind, could you update the Linux binaries also with the same fix.

**Comment by bfritscher** [comment]
@option-greek had finally time to setup automated build, can you test this version? https://github.com/bfritscher/typesense-dashboard/releases/tag/v1.0.1 It should include the self signed fix.

**Comment by option-greek** [comment]
It works great @bfritscher. Thank you!
