### ISSUE TITLE
Option to clear typesense cache

### ISSUE THREAD

**Issue by webcredo** [bfritscher/typesense-dashboard#50]
It would be great to have an option to clear the typesense cache.

**Comment by bfritscher** [comment]
Hi, what cache are you referring to?
The application only saves login history and you can clear this history on the login screen as well as the logout dropdown

![image](https://github.com/bfritscher/typesense-dashboard/assets/338973/6d66b16e-c4a4-42f3-8f7d-f457e0bf569f)

<img width="197" alt="image" src="https://github.com/bfritscher/typesense-dashboard/assets/338973/75f0b03c-d8b5-44af-8481-a0bc9d7acda5">

**Comment by webcredo** [comment]
@bfritscher I mean about typesense cache not the dashboard https://typesense.org/docs/26.0/api/cluster-operations.html#clear-cache

**Comment by webcredo** [comment]
> Added support for some server operations in version 1.7.0

Great!
