### ISSUE TITLE
How to add Cors ?

### ISSUE THREAD

**Issue by manchumahara** [bfritscher/typesense-dashboard#6]
I installed typesense in a ubuntu machine. How can I start the server with cors enabled ?
I tried this

 sudo systemctl start typesense-server.service --enable-cors=true
 
 But this doesn't work 

Can I set 
enable-cors = true  in config file  of tyepsense ?

**Comment by bfritscher** [comment]
Hi, I used the docker version with the command  --data-dir /data --enable-cors --api-key=...
I suppose that you have to edit the service file to add the arguments if it is not setup to receive arguments via systemctl or edit the right config file.

https://typesense.org/docs/0.22.2/api/server-configuration.html#using-command-line-arguments
https://typesense.org/docs/0.22.2/api/server-configuration.html#using-a-configuration-file
