### ISSUE TITLE
Support symbols_to_index and locale values on synonyms

### ISSUE THREAD

**Issue by elliot-sawyer** [bfritscher/typesense-dashboard#68]
**Is your feature request related to a problem? Please describe.**
Support symbols_to_index and locale values when adding or updating synonyms through the Dashboard.  Currently you can submit these fields via the API, but you cannot manage them with the dashboard.

**Describe the solution you'd like**
A dropdown for supported locales, and a textfield for symbols_to_index

**Describe alternatives you've considered**
The only way to add or update these at the moment is through a CURL request or via SDK

**Additional context**

**Comment by bfritscher** [comment]
Hi, which version did you test? It was already added to version 1.6.0

![image](https://github.com/user-attachments/assets/0358f84d-e487-4c0f-b81f-f9ee10537904)

**Comment by elliot-sawyer** [comment]
Nice!  Was using the latest one from docker: `ghcr.io/bfritscher/typesense-dashboard:latest`, but I haven't pulled in a while  :+1:

**Comment by elliot-sawyer** [comment]
I pulled the latest image and it works perfectly!  :+1:
