### ISSUE TITLE
Getting error while trying to import data on Mac

### ISSUE THREAD

**Issue by bigraymasoom** [bfritscher/typesense-dashboard#71]
Hello community, i am using the desktop client for Mac and I am facing issue while trying to import the documents. When I click the button of import from file I get this error  `0: this.$store.getters.node/api.importFile is not a function`. Is this a bug or only i'm facing this issue. And how I can fix this issue. Thanks

**Comment by bfritscher** [comment]
@bigraymasoom  Yes, it seems to be a bug, can you try the new 1.9.2 to see if its fixed for your case also? https://github.com/bfritscher/typesense-dashboard/releases/tag/v1.9.2

**Comment by bigraymasoom** [comment]
Thanks a lot, its fixed now.
